package com.reasoning.common.auth.service;

import com.eatthepath.otp.TimeBasedOneTimePasswordGenerator;

import org.apache.commons.codec.binary.Base32;
import org.springframework.stereotype.Service;

import java.security.InvalidKeyException;
import java.time.Instant;

import javax.crypto.spec.SecretKeySpec;

@Service
public class TotpService {
    private static final Base32 BASE32 = new Base32();
    private final TimeBasedOneTimePasswordGenerator generator =
            new TimeBasedOneTimePasswordGenerator();

    /**
     * Encodes a random TOTP secret as unpadded base32 for authenticator apps.
     *
     * @param rawSecret secret bytes, at least 20 bytes for this project
     * @return uppercase base32 text without separators or padding
     */
    public String encodeBase32(byte[] rawSecret) {
        return BASE32.encodeToString(rawSecret).replace("=", "");
    }

    /**
     * Decodes unpadded base32 text generated by the service.
     *
     * @param text uppercase base32 text without separators
     * @return decoded bytes
     * @throws AuthException when the alphabet or trailing bits are invalid
     */
    public byte[] decodeBase32(String text) {
        if (text == null || !text.matches("^[A-Z2-7]+$") || (text.length() * 5) % 8 >= 5) {
            throw AuthException.unprocessable("INVALID_TOTP_SECRET");
        }
        byte[] decoded = BASE32.decode(text);
        if (!encodeBase32(decoded).equals(text)) {
            throw AuthException.unprocessable("INVALID_TOTP_SECRET");
        }
        return decoded;
    }

    /**
     * Verifies a six-digit TOTP within the project ±1 step window.
     *
     * @param secretBase32 TOTP secret in base32
     * @param totp six decimal digits, including leading zeroes
     * @param now server verification time
     * @param lastStep last accepted step; equal or older steps are rejected
     * @return accepted time step
     * @throws AuthException when the code is invalid or reuses a consumed step
     */
    public long verify(String secretBase32, String totp, Instant now, Long lastStep) {
        if (totp == null || !totp.matches("^[0-9]{6}$")) {
            throw AuthException.unprocessable("INVALID_TOTP");
        }
        byte[] secret = decodeBase32(secretBase32);
        long current = now.getEpochSecond() / 30;
        for (long step = current - 1; step <= current + 1; step++) {
            if (step >= 0
                    && (lastStep == null || step > lastStep)
                    && code(secret, step).equals(totp)) {
                return step;
            }
        }
        throw AuthException.unprocessable("INVALID_TOTP");
    }

    /**
     * Creates a current TOTP value for tests and command-line diagnostics.
     *
     * @param secretBase32 TOTP secret in base32
     * @param at timestamp to evaluate
     * @return six-digit code
     */
    public String code(String secretBase32, Instant at) {
        return code(decodeBase32(secretBase32), at.getEpochSecond() / 30);
    }

    private String code(byte[] secret, long step) {
        try {
            return generator.generateOneTimePasswordString(
                    new SecretKeySpec(secret, generator.getAlgorithm()),
                    Instant.ofEpochSecond(step * 30));
        } catch (InvalidKeyException e) {
            throw AuthException.unavailable("AUTH_UNAVAILABLE");
        }
    }
}
